//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Ajax_Bootstrap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public short BlogID { get; set; }
        public string BlogBaslik { get; set; }
        public string BlogIcerik { get; set; }
        public string BlogGorselUrl { get; set; }
        public short BlogYazarID { get; set; }
        public Nullable<System.DateTime> BlogKayitTarih { get; set; }
        public Nullable<System.DateTime> BlogGuncellemeTarih { get; set; }
        public Nullable<bool> BlogAktif { get; set; }
    }
}
