//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Ajax_Bootstrap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanici()
        {
            this.KullaniciAktif = 1;
            this.KullaniciYetki = 3;
        }
    
        public short KullaniciID { get; set; }
        public string KullaniciAdSoyad { get; set; }
        public System.DateTime KullaniciDogumTarih { get; set; }
        public string KullaniciEposta { get; set; }
        public string KullaniciParola { get; set; }
        public string KullaniciFotoUrl { get; set; }
        public Nullable<System.DateTime> KullaniciKayitTarih { get; set; }
        public Nullable<System.DateTime> KullaniciKayıtSilmeTarihi { get; set; }
        public Nullable<int> KullaniciAktif { get; set; }
        public Nullable<int> KullaniciYetki { get; set; }
    }
}
